FROM postgres
ENV POSTGRES_PASSWORD docker
ENV POSTGRES_DB world
COPY world.sql /docker-entrypoint-initdb.d/

# docker build -t my-postgres-db -f ./Dockerfile_postgress ./
# docker run -d --name my-postgres-db -p 5432:5432 my-postgres-db
# https://dev.to/andre347/how-to-easily-create-a-postgres-database-in-docker-4moj
